In [21]:
import numpy as np

In [55]:
A = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],  
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],  
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0], 
    [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],  
    [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0], 
    [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],  
    [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
])

In [114]:
def adjacency_pageRanke(A,alpha=0.83,eps=1e-6) :
    num_link_of_page  = np.sum(A,axis=1)

    D = np.zeros(A.shape)
    for i , num  in enumerate (num_link_of_page) : 
        if num == 0  :
            D[i] = 1/A.shape[0]
        else : 
            D[i] = (1-alpha) /A.shape[0]

    M= np.where(num_link_of_page[:, np.newaxis] == 0, 
             0, 
             A * alpha / num_link_of_page[:, np.newaxis])
    
    P =M+D
    R = np.ones(A.shape[0])/A.shape[0]

    l=0
    R1 = np.dot(R,P)
    norme = np.sum(np.abs(R - R1))
    while norme >=  eps :
        R = R1
        R1 = np.dot(R,P)
        norme = np.sum(np.abs(R - R1))
        l=l+1


    return np.round(R1 *100,2) ,l


In [115]:
rank,l  = adjacency_pageRanke(A,0.85,1e-6 ) 

C:\Users\Zakroum Hicham\AppData\Local\Temp\ipykernel_3664\550085552.py:13: RuntimeWarning: invalid value encountered in divide
  A * alpha / num_link_of_page[:, np.newaxis])


In [116]:
rank

array([ 3.28, 38.44, 34.29,  3.91,  8.09,  3.91,  1.62,  1.62,  1.62,
        1.62,  1.62])

In [105]:
l
    


80

In [120]:
edges = {
    'A': [],
    'B': ['C'],
    'C': ['B'],
    'D': ['A', 'B'],
    'E': ['B', 'D', 'F'],
    'F': ['B', 'E'],
    'G': ['B', 'E'],
    'H': ['B', 'E'],
    'I': ['E','B'],
    'L': ['E'],
    'M': ['E']
}
nodes = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'L', 'M']

In [121]:
def graph_pagerank(nodes,edges):
   n = len(nodes)

   adjacency_matrix = np.zeros((n, n))

   for node, outgoing_edges in edges.items():
       for edge in outgoing_edges:
           adjacency_matrix[nodes.index(edge), nodes.index(node)] = 1
           
   rank,l= adjacency_pageRanke(adjacency_matrix.T,0.85,10 ** -6 ) 

   return  rank,l

In [122]:
rank,l= graph_pagerank(nodes,edges)

C:\Users\Zakroum Hicham\AppData\Local\Temp\ipykernel_3664\550085552.py:13: RuntimeWarning: invalid value encountered in divide
  A * alpha / num_link_of_page[:, np.newaxis])


In [123]:
rank

array([ 3.28, 38.44, 34.29,  3.91,  8.09,  3.91,  1.62,  1.62,  1.62,
        1.62,  1.62])

In [124]:
l

80

In [128]:
import xmltodict


def xml_pageRank(file_name):


    with open(file_name,"rb") as xml:
        data = xmltodict.parse(xml)

    # Extract the nodes and edges
    nodes = [node['@id'] for node in data['graph']['nodes']['node']]


    edges = {node: [] for node in nodes}
    for edge in data['graph']['edges']['edge']:
        source = edge['@source']
        target = edge['@target']
        edges[source].append(target)
    
    return graph_pagerank(nodes,edges)

rank, l = xml_pageRank("test.xml")

C:\Users\Zakroum Hicham\AppData\Local\Temp\ipykernel_3664\550085552.py:13: RuntimeWarning: invalid value encountered in divide
  A * alpha / num_link_of_page[:, np.newaxis])


In [129]:
rank

array([ 3.28, 38.44, 34.29,  3.91,  8.09,  3.91,  1.62,  1.62,  1.62,
        1.62,  1.62])

In [167]:
import networkx as nx
# Create a directed graph from the links
G = nx.DiGraph()

# Add edges to the graph
for source, targets in edges.items():
    for target in targets:
        G.add_edge(source, target)

# Calculate PageRank
pagerank = nx.pagerank(G)
for i,j in pagerank.items():
    print(i,j)
# Add PageRank values to each node as an attribute
for node in G.nodes():
    G.nodes[node]['pagerank'] = round(pagerank[node]*100,2)
# Print PageRank values
print([round(pagerank[i]*100,2) for i in sorted(pagerank)])


B 0.38439863456604384
C 0.3429125997558898
D 0.039087092099966095
A 0.03278149315934399
E 0.08088569323449774
F 0.039087092099966095
G 0.016169479016858404
H 0.016169479016858404
I 0.016169479016858404
L 0.016169479016858404
M 0.016169479016858404
[3.28, 38.44, 34.29, 3.91, 8.09, 3.91, 1.62, 1.62, 1.62, 1.62, 1.62]


In [138]:
from pyvis.network import Network

In [164]:
nt = Network(height="100vh", width="100%", directed=True,select_menu=True)
# Add nodes and edges to the Pyvis network
for node in G.nodes():
    # Add the node with PageRank value as a title
    nt.add_node(node, label=f"{node}\n{round(pagerank[node] * 100, 2)}%", value=pagerank[node])

for source, target in G.edges():
    nt.add_edge(source, target)

# Customize the layout
nt.force_atlas_2based(central_gravity=0.015, gravity=-40)
# nt.show_buttons(filter_=['physics'])
nt.write_html("graph.html")